In [1]:
import pandas as pd
import numpy as np
from scipy.optimize import fmin_tnc
from numpy import linalg as LA
import warnings

In [2]:
df_1 = pd.read_csv("/Users/dengkun/Desktop/598/project4/project4_data_part1.csv")
df_2 = pd.read_csv("/Users/dengkun/Desktop/598/project4/project4_data_part2.csv")
df_3 = pd.read_csv("/Users/dengkun/Desktop/598/project4/project4_data_part3.csv")
df_4 = pd.read_csv("/Users/dengkun/Desktop/598/project4/project4_data_part4.csv")
df_5 = pd.read_csv("/Users/dengkun/Desktop/598/project4/project4_data_part5.csv")
df_6 = pd.read_csv("/Users/dengkun/Desktop/598/project4/project4_data_part6.csv")
df_7 = pd.read_csv("/Users/dengkun/Desktop/598/project4/project4_data_part7.csv")
df_8 = pd.read_csv("/Users/dengkun/Desktop/598/project4/project4_data_part8.csv")
df_9 = pd.read_csv("/Users/dengkun/Desktop/598/project4/project4_data_part9.csv")
df_10 = pd.read_csv("/Users/dengkun/Desktop/598/project4/project4_data_part10.csv")

In [3]:
df_1

y  x1  x2        x3  x4        x5        x6        x7  x8  x9  ...  \
0       1   1   0 -0.266401  76 -0.626454 -0.131414 -1.538147   0   0  ...   
1       0   0   0  0.790325  27  0.183643 -1.041263  2.004025   0   1  ...   
2       0   0   0  0.870765  49 -0.835629  0.052375 -1.705432   0   0  ...   
3       1   0   0 -0.789834  68  1.595281  0.388524 -1.216284   0   0  ...   
4       1   1   1  1.026132  39  0.329508 -0.672833  0.936360   0   0  ...   
...    ..  ..  ..       ...  ..       ...       ...       ...  ..  ..  ...   
999995  1   0   1 -1.046101  62  0.924487  0.967299 -1.010999   0   1  ...   
999996  1   1   0  1.219793  78 -0.013514 -1.617849  0.181478   0   0  ...   
999997  0   1   1  0.638136  41 -0.604059 -0.175740 -0.776754   0   1  ...   
999998  1   1   1 -0.050493  35  1.628763  0.658668  1.750200   0   1  ...   
999999  0   1   0 -0.970948  21  0.693750  0.143222 -1.421764   0   0  ...   

             x16       x17       x18  x19       x20       x21  x22  x23  \
0      -0.012636 -0.618777 -1.358483    0  1.705226  0.225172    1    0   
1       1.300464  0.087875 -1.612829    1 -1.391515 -1.054689    0    0   
2       0.710917  0.823984 -2.019758    1  0.306845 -1.053518    1    0   
3       1.423246  1.121940  0.303652    0  1.491366  0.218625    1    0   
4       0.851831 -0.765552  0.433107    1  0.066660 -0.294293    1    0   
...          ...       ...       ...  ...       ...       ...  ...  ...   
999995  0.538306 -0.601550  0.368097    1 -0.269165 -1.248270    1    0   
999996 -1.047338  1.109438 -1.481046    1 -2.374712 -0.615563    1    0   
999997  0.269186 -0.417272 -0.207349    1  0.549681 -1.558586    1    0   
999998 -1.211304 -0.172090 -0.969454    1 -0.844721  1.153384    1    0   
999999 -0.717955  0.214231  1.025393    1  0.977390  0.512050    1    0   

             x24       x25  
0       0.315782 -0.229762  
1      -0.562159  0.266106  
2      -1.980564  0.563185  
3      -0.597842 -0.284233  
4      -0.010230 -0.364782  
...          ...       ...  
999995 -0.459845 -0.721639  
999996  0.187222 -0.199463  
999997  0.668082 -1.155122  
999998 -0.722195  0.377680  
999999  0.153170 -2.044720  

[1000000 rows x 26 columns]

In [4]:
X_1 = df_1.iloc[:, 1:]
y_1 = df_1.iloc[:,0]
X_2 = df_2.iloc[:, 1:]
y_2 = df_2.iloc[:,0]
X_3 = df_3.iloc[:, 1:]
y_3 = df_3.iloc[:,0]
X_4 = df_4.iloc[:, 1:]
y_4 = df_4.iloc[:,0]
X_5 = df_5.iloc[:, 1:]
y_5 = df_5.iloc[:,0]
X_6 = df_6.iloc[:, 1:]
y_6 = df_6.iloc[:,0]
X_7 = df_7.iloc[:, 1:]
y_7 = df_7.iloc[:,0]
X_8 = df_8.iloc[:, 1:]
y_8 = df_8.iloc[:,0]
X_9 = df_9.iloc[:, 1:]
y_9 = df_9.iloc[:,0]
X_10 = df_10.iloc[:, 1:]
y_10 = df_10.iloc[:,0]

In [5]:
y_1 = np.ravel(y_1)
y_2 = np.ravel(y_2)
y_3 = np.ravel(y_3)
y_4 = np.ravel(y_4)
y_5 = np.ravel(y_5)
y_6 = np.ravel(y_6)
y_7 = np.ravel(y_7)
y_8 = np.ravel(y_8)
y_9 = np.ravel(y_9)
y_10 = np.ravel(y_10)

In [ ]:
#estimator = SVR(kernel="linear")
#selector = RFE(estimator, n_features_to_select=5, step=1)
#selector = selector.fit(X_1, y_1)
#selector.support_

In [19]:
#selector.score(X_1,y_1)

In [6]:
X_1 = np.c_[np.ones((X_1.shape[0], 1)), X_1]
X_2 = np.c_[np.ones((X_2.shape[0], 1)), X_2]
X_3 = np.c_[np.ones((X_3.shape[0], 1)), X_3]
X_4 = np.c_[np.ones((X_4.shape[0], 1)), X_4]
X_5 = np.c_[np.ones((X_5.shape[0], 1)), X_5]
X_6 = np.c_[np.ones((X_6.shape[0], 1)), X_6]
X_7 = np.c_[np.ones((X_7.shape[0], 1)), X_7]
X_8 = np.c_[np.ones((X_8.shape[0], 1)), X_8]
X_9 = np.c_[np.ones((X_9.shape[0], 1)), X_9]
X_10 = np.c_[np.ones((X_10.shape[0], 1)), X_10]

In [7]:
theta = np.random.randn(X_1.shape[1])
p = 1
e = 0.0000001
beta_0 = np.random.randn(X_1.shape[1])
u_1 = np.random.randn(X_1.shape[1])
u_2 = np.random.randn(X_2.shape[1])
u_3 = np.random.randn(X_3.shape[1])
u_4 = np.random.randn(X_4.shape[1])
u_5 = np.random.randn(X_5.shape[1])
u_6 = np.random.randn(X_6.shape[1])
u_7 = np.random.randn(X_7.shape[1])
u_8 = np.random.randn(X_8.shape[1])
u_9 = np.random.randn(X_9.shape[1])
u_10 = np.random.randn(X_10.shape[1])

In [8]:
def sigmoid(x):
    # Activation function used to map any real value between 0 and 1
    return 1 / (1 + np.exp(-x))

In [9]:
def net_input(theta, x):
    # Computes the weighted sum of inputs
    return np.dot(x, theta)

In [10]:
def probability(theta, x):
    # Returns the probability after passing through sigmoid
    return sigmoid(net_input(theta, x))

In [11]:
def cost_function(theta, x, y, beta_k, u_k):
    # Computes the cost function for all the training samples
    m = x.shape[0]
    total_cost = -(1 / m) * np.sum(
        y * np.log(e + probability(theta, x)) + (1 - y) * np.log(e + 
            1 - probability(theta, x))) + (p/2) * (LA.norm((theta - beta_k + u_k), 2))**2
    return total_cost

In [12]:
def gradient(theta, x, y, beta_k, u_k):
    # Computes the gradient of the cost function at the point theta
    m = x.shape[0]
    return (1 / m) * (np.dot(x.T, sigmoid(net_input(theta, x)) - y) + p*(theta - beta_k + u_k))

In [13]:
def fit(x, y, theta, beta_k, u_k):
    opt_weights = fmin_tnc(func=cost_function, x0=theta,
                  fprime=gradient,args=(x, y, beta_k, u_k))
    return opt_weights[0]

In [14]:
def predict(x, parameters):
    theta = parameters[:, np.newaxis]
    return probability(theta, x)
def accuracy(x, actual_classes, parameters, probab_threshold=0.5):
    predicted_classes = (predict(x, parameters) >= 
                         probab_threshold).astype(int)
    predicted_classes = predicted_classes.flatten()
    accuracy = np.mean(predicted_classes == actual_classes)
    return accuracy * 100

In [15]:
warnings.filterwarnings('ignore')

## First iteration

In [16]:
beta1 = fit(X_1, y_1, theta, beta_0, u_1)
beta2 = fit(X_2, y_2, theta, beta_0, u_2)
beta3 = fit(X_3, y_3, theta, beta_0, u_3)
beta4 = fit(X_4, y_4, theta, beta_0, u_4)
beta5 = fit(X_5, y_5, theta, beta_0, u_5)
beta6 = fit(X_6, y_6, theta, beta_0, u_6)
beta7 = fit(X_7, y_7, theta, beta_0, u_7)
beta8 = fit(X_8, y_8, theta, beta_0, u_8)
beta9 = fit(X_9, y_9, theta, beta_0, u_9)
beta10 = fit(X_10, y_10, theta, beta_0, u_10)

In [17]:
beta1_ave = 1/10*(beta1+beta2+beta3+beta4+beta5+beta6+beta7+beta8+beta9+beta10)

In [18]:
u_12 = u_1 + beta1 - beta1_ave
u_22 = u_2 + beta2 - beta1_ave
u_32 = u_3 + beta3 - beta1_ave
u_42 = u_4 + beta4 - beta1_ave
u_52 = u_5 + beta5 - beta1_ave
u_62 = u_6 + beta6 - beta1_ave
u_72 = u_7 + beta7 - beta1_ave
u_82 = u_8 + beta8 - beta1_ave
u_92 = u_9 + beta9 - beta1_ave
u_102 = u_10 + beta10 - beta1_ave

## Second iteration

In [19]:
beta12 = fit(X_1, y_1, theta, beta1_ave, u_12)
beta22 = fit(X_2, y_2, theta, beta1_ave, u_22)
beta32 = fit(X_3, y_3, theta, beta1_ave, u_32)
beta42 = fit(X_4, y_4, theta, beta1_ave, u_42)
beta52 = fit(X_5, y_5, theta, beta1_ave, u_52)
beta62 = fit(X_6, y_6, theta, beta1_ave, u_62)
beta72 = fit(X_7, y_7, theta, beta1_ave, u_72)
beta82 = fit(X_8, y_8, theta, beta1_ave, u_82)
beta92 = fit(X_9, y_9, theta, beta1_ave, u_92)
beta102 = fit(X_10, y_10, theta, beta1_ave, u_102)

In [20]:
beta2_ave = 1/10*(beta12+beta22+beta32+beta42+beta52+beta62+beta72+beta82+beta92+beta102)

In [21]:
u_13 = u_12 + beta12 - beta2_ave
u_23 = u_22 + beta22 - beta2_ave
u_33 = u_32 + beta32 - beta2_ave
u_43 = u_42 + beta42 - beta2_ave
u_53 = u_52 + beta52 - beta2_ave
u_63 = u_62 + beta62 - beta2_ave
u_73 = u_72 + beta72 - beta2_ave
u_83 = u_82 + beta82 - beta2_ave
u_93 = u_92 + beta92 - beta2_ave
u_103 = u_102 + beta102 - beta2_ave

## Third iteration

In [22]:
beta13 = fit(X_1, y_1, theta, beta2_ave, u_13)
beta23 = fit(X_2, y_2, theta, beta2_ave, u_23)
beta33 = fit(X_3, y_3, theta, beta2_ave, u_33)
beta43 = fit(X_4, y_4, theta, beta2_ave, u_43)
beta53 = fit(X_5, y_5, theta, beta2_ave, u_53)
beta63 = fit(X_6, y_6, theta, beta2_ave, u_63)
beta73 = fit(X_7, y_7, theta, beta2_ave, u_73)
beta83 = fit(X_8, y_8, theta, beta2_ave, u_83)
beta93 = fit(X_9, y_9, theta, beta2_ave, u_93)
beta103 = fit(X_10, y_10, theta, beta2_ave, u_103)

In [23]:
beta3_ave = 1/10*(beta13+beta23+beta33+beta43+beta53+beta63+beta73+beta83+beta93+beta103)

In [24]:
u_14 = u_13 + beta13 - beta3_ave
u_24 = u_23 + beta23 - beta3_ave
u_34 = u_33 + beta33 - beta3_ave
u_44 = u_43 + beta43 - beta3_ave
u_54 = u_53 + beta53 - beta3_ave
u_64 = u_63 + beta63 - beta3_ave
u_74 = u_73 + beta73 - beta3_ave
u_84 = u_83 + beta83 - beta3_ave
u_94 = u_93 + beta93 - beta3_ave
u_104 = u_103 + beta103 - beta3_ave

## Fourth iteration

In [25]:
beta14 = fit(X_1, y_1, theta, beta3_ave, u_14)
beta24 = fit(X_2, y_2, theta, beta3_ave, u_24)
beta34 = fit(X_3, y_3, theta, beta3_ave, u_34)
beta44 = fit(X_4, y_4, theta, beta3_ave, u_44)
beta54 = fit(X_5, y_5, theta, beta3_ave, u_54)
beta64 = fit(X_6, y_6, theta, beta3_ave, u_64)
beta74 = fit(X_7, y_7, theta, beta3_ave, u_74)
beta84 = fit(X_8, y_8, theta, beta3_ave, u_84)
beta94 = fit(X_9, y_9, theta, beta3_ave, u_94)
beta104 = fit(X_10, y_10, theta, beta3_ave, u_104)

In [26]:
beta4_ave = 1/10*(beta14+beta24+beta34+beta44+beta54+beta64+beta74+beta84+beta94+beta104)

In [28]:
accuracy(X_1,y_1,beta1_ave)

59.495799999999996

In [29]:
accuracy(X_1,y_1,beta2_ave)

68.4081

In [30]:
accuracy(X_1,y_1,beta3_ave)

71.6114

In [31]:
accuracy(X_1,y_1,beta4_ave)

71.5485

In [32]:
accuracy(X_2,y_2,beta1_ave)

71.6599

In [33]:
accuracy(X_2,y_2,beta2_ave)

80.4553

In [34]:
accuracy(X_2,y_2,beta3_ave)

83.0981

In [35]:
accuracy(X_2,y_2,beta4_ave)

83.10650000000001

In [36]:
accuracy(X_3,y_3,beta1_ave)

87.5809

In [37]:
accuracy(X_3,y_3,beta2_ave)

91.6031

In [38]:
accuracy(X_3,y_3,beta3_ave)

91.9286

In [39]:
accuracy(X_3,y_3,beta4_ave)

92.65820000000001

In [40]:
beta1_ave

array([-1.08692828,  0.17904039, -0.30641946, -0.17491705,  0.15785407,
       -0.10405104, -0.01348491, -0.08888742,  0.59594043, -0.1038777 ,
        0.29056346,  0.16184241, -0.20955583, -0.02898546,  0.40153049,
        0.04075134, -0.1454075 , -0.00984641, -0.14660507, -1.14366744,
        0.00840385,  0.11551567,  0.05644161, -0.13466436,  0.05869679,
        0.03094733])

In [64]:
beta2_ave

array([-0.80754976,  1.25492791, -0.59142789,  0.09285077,  0.0607104 ,
        0.13515942,  0.12456238, -0.2413886 , -0.00264679, -0.36982382,
        0.34776491, -0.10301688, -0.40149738,  0.33053816,  0.01667488,
       -0.07406862, -0.27180328,  0.15691345, -0.5966577 , -0.24825887,
       -0.19626297,  0.32554148, -0.52732139,  0.0614234 ,  0.07181017,
        0.04306759])

In [65]:
beta3_ave

array([-9.72256882e-01,  1.32017940e+00, -5.19684552e-01,  1.12857780e-01,
        6.90861567e-02,  1.40131487e-01,  1.34160170e-01, -2.51667256e-01,
        8.91477950e-04, -4.15191857e-01,  3.25721487e-01, -1.05750108e-01,
       -3.94514984e-01,  2.26465023e-01,  2.24365375e-03, -7.77181391e-02,
       -2.61425725e-01,  1.71815973e-01, -4.29336518e-01, -3.00243936e-01,
       -2.40732029e-01,  3.75960531e-01, -5.07934578e-01,  1.57306966e-01,
        7.00291377e-02,  5.50160557e-02])

In [66]:
beta4_ave

array([-1.48027245e+00,  1.39425252e+00, -3.22622789e-01,  2.34021222e-02,
        7.76595546e-02,  4.03700489e-02,  5.87577743e-02, -1.59256073e-01,
       -1.43281883e-02, -2.27287811e-01,  2.08149633e-01, -7.54892411e-02,
       -2.59500666e-01,  1.15339489e-01, -5.53609903e-03, -6.78042959e-02,
       -1.47857704e-01,  8.20999800e-02, -3.64050398e-01, -3.65847137e-01,
       -1.36308266e-01,  4.35989960e-01, -2.81029415e-01,  3.07699940e-02,
        2.36453876e-02, -5.03989154e-04])